### ISSUE TITLE
sqlathanor.errors.CSVStructureError: expected 0 fields, found 1

### ISSUE THREAD

**Issue by mulloa-8451** [insightindustry/sqlathanor#88] opened 2020-04-07 12:36 UTC
**sqlAthanor is generating the the error:** "sqlathanor.errors.CSVStructureError: expected 0 fields, found 1" 

**This is occurring on data formatted as:**  "DEPARTMENT, ESP AD SECTION, AD TYPE, PROGO SLICER, , , , , , , , , , , , , , , , , , ,"

**The error details:**
    Traceback (most recent call last):
      File "test5.py", line 36, in <module>
        my_instance = Asset.new_from_csv(','.join(row), delimiter=' ')

**My code is as follows:**
with open(csv_Source, 'r') as csv_file:
    csv_records = csv.reader(csv_file, delimiter = ',')
    my_record_instances = [] #?
    for row in csv_records:
        print(', '.join(row))
        my_instance = Asset.new_from_csv(','.join(row), delimiter=' ')
        my_record_instances.append(my_instance)

I have not been able to ID the issue. Can you provide some insight into what might be causing this?

**Comment by insightindustry** [comment] 2020-04-07 16:40
@mulloa-8451 - Thanks for your note! Happy to take a look and see if I can help. I suspect the issue is tied to the serialization / deserialization configuration as applied to your `Asset` class. Have you enabled the fields that you want to serialize/deserialize to/from CSV in that class? Here's a link to some documentation on that configuration: https://sqlathanor.readthedocs.io/en/latest/using.html#configure-serialization-de-serialization

The way SQLAthanor works, you have to explicitly tell SQLAthanor that "this is a field that we expect to find in a CSV". The exception that you are getting suggests that SQLAthanor doesn't see any CSV-enabled fields, so it's kicking up that error. 

If you have configured CSV support on your `Asset` class and it is still generating that exception, would you be able to share the code for that class? (if you don't want to post it in a GH issue, feel free to email it to me).

**Comment by mulloa-8451** [comment] 2020-04-07 17:43
OK - I've looked into the serialization and determined the problem was caused by the instantiation of the Model Class. I incorrectly left it instantiateed using db.Model (i.e., SQLAlchemy), and not using the model format defined by sqlAthanor.

**One issue remains though:**
How do I save the records to the database after the code executes?
```
with open(csv_Source) as csv_file:
    csv_records = csv.reader(csv_file, delimiter = ',')
    my_record_instances = [] #?
    for row in csv_records:
        print(', '.join(row))
        my_instance = Asset.new_from_csv(','.join(row), delimiter=',')
        my_record_instances.append(my_instance)
```

**Comment by insightindustry** [comment] 2020-04-07 18:01
Ah - got it. Glad you were able to fix the issue! 

To commit your instances to the DB after you've de-serialized them, you can just leverage SQLAlchemy's existing syntax for that. So using your SQLAlchemy session object, you essentially call ``session.commit()`` and it will commit the instances to your DB the same as SQLAlchemy itself would ordinarily. Here's some further SQLAlchemy documentation you  may find helpful:  https://docs.sqlalchemy.org/en/13/orm/session_basics.html#committing

Note that your instances will still need to conform to the constraints you've created in your model / database, but SQLAlchemy should handle the process of executing the transaction and (if necessary) rolling back as needed. That link above should provide a lot more insight into how SQLAlchemy itself manages sessions+transactions.

**Comment by insightindustry** [comment] 2020-04-07 23:51
Judging by the thumbs up, I’m assuming this closes out the question and you were able to get stuff working. Hopefully that’s the case! I’ll close this issue, but if you run into further trouble just let me know. Always happy to help.

**Closed by insightindustry** 2020-04-07 23:51 UTC
Labels: question

**Comment by justinpaulturner** [comment] 2020-10-11 19:47
Hello, 

I am having the same error as the previous commenter but I believe I am instantiating the model correctly. Below is my code for trying to create a database with the corresponding csv file.

```
#create_db.py
from sqlathanor import FlaskBaseModel, initialize_flask_sqlathanor
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import csv

application = Flask(__name__)
application.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
db = SQLAlchemy(application, model_class = FlaskBaseModel)
db = initialize_flask_sqlathanor(db)

db.create_all()

class Gps(db.Model):
    __tablename__ = 'gps'
    id = db.Column(db.Integer, primary_key=True)
    message_id = (db.String())
    dlc = (db.Float())
    payload = (db.String())
    puc_id = (db.Integer())
    ts = (db.String())
    gps_id = (db.Float())
    latitude = (db.Float())
    longitude = (db.Float())
    groundspeed = (db.Float())
    truecourse = (db.Float())
    
my_record_instances = []
with open('gps_can_data.csv', 'r') as csv_file:
    csv_records = csv.reader(csv_file, delimiter = ',')
    for row in csv_records:
        my_instance = Gps.new_from_csv(','.join(row), 
                                         delimiter = ',')
        my_record_instances.append(my_instance)
```
Below is a preview of the csv and the requirements.txt.
**CSV:**
```
message_id,dlc,payload,puc_id,ts,gps_id,latitude,longitude,groundspeed,truecourse
,,,8765,2016-10-28 05:00:00,681665533,35.05875000000000,-80.38093000000000,0.01841250000000,0.00000000000000
0CFF1003,8,FFFFFFFFFFFFFFFF,8765,2016-10-28 05:00:00,,,,,
1CFFFF17,8,9AFF64FFFFFFFFFF,8765,2016-10-28 05:00:00,,,,,
0CFFFE17,8,3317FFFFFFFFFFFF,8765,2016-10-28 05:00:00,,,,,
```
Requirements.txt:
```
aniso8601==8.0.0
attrs==20.2.0
backcall==0.2.0
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
decorator==4.4.2
Flask==1.1.2
Flask-Markdown==0.3
Flask-RESTful==0.3.8
Flask-SQLAlchemy==2.4.4
idna==2.10
ipykernel==5.3.4
ipython==7.18.1
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.17.2
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-core==4.6.3
Markdown==3.3
MarkupSafe==1.1.1
numpy==1.19.2
pandas==1.1.2
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.7
ptyprocess==0.6.0
Pygments==2.7.1
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
pyzmq==19.0.2
requests==2.24.0
simplejson==3.17.2
six==1.15.0
SQLAlchemy==1.3.19
sqlathanor==0.5.1
tornado==6.0.4
traitlets==5.0.4
urllib3==1.25.10
validator-collection==1.4.2
wcwidth==0.2.5
Werkzeug==1.0.1

```

**Comment by insightindustry** [comment] 2020-10-12 17:37
Hi @justinpaulturner : Thanks for the question!

I think you're running into the same issue as the OP had been running into - namely that while you are initializing your SQLAlchemy model correctly, you have not told SQLAthanor which columns to "look for" in the CSV-serialized format. 

In order to deserialize from CSV (or from JSON or anything else), SQLAthanor needs to know which model attributes (database columns) it should expect to find. This applies to both which columns to find on deserialization and which columns to output when serializing, for security reasons. You can find detailed documentation on how to configure this here: https://sqlathanor.readthedocs.io/en/latest/using.html#configure-serialization-de-serialization

**Comment by justinpaulturner** [comment] 2020-10-12 17:39
That makes perfect sense! This resolved my error. Thank you!
